name: task validate commit on b SDK-974
on:
  push:
    branches: [ task/cicd/SDK-974 ]

jobs:
  lint-staticChecks-test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup actions.
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Check lint
        if: always()
        run: ./gradlew :clevertap-core:lint
        # todo run for all . need to remove the dependency on google services

      - name: Upload Lint results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lint_results
          path:  |
            clevertap-core/build/reports/lint-results.html
            clevertap-hms/build/reports/lint-results.html
            clevertap-xps/build/reports/lint-results.html
            clevertap-geofence/build/reports/lint-results.html
            clevertap-pushTemplates/build/reports/lint-results.html
            sample/build/reports/lint-results.html

      - name: CodeAnalysis via  detekt
        if: always()
        run: ./gradlew :clevertap-core:detekt
        # todo run for all . need to remove the dependency on google services


      - name: Upload detekt results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: detekt_results
          path:  |
            clevertap-core/build/reports/detekt/detekt.html
            clevertap-hms/build/reports/detekt/detekt.html
            clevertap-xps/build/reports/detekt/detekt.html
            clevertap-geofence/build/reports/detekt/detekt.html
            clevertap-pushTemplates/build/reports/detekt/detekt.html
            sample/build/reports/detekt/detekt.html

      - name: CodeAnalysis via  checkstyle
        if: always()
        run: ./gradlew :clevertap-core:checkstyle

      - name: Upload checkstyle results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle_results
          path: |
            clevertap-core/build/reports/checkstyle/checkstyle.html
            clevertap-hms/build/reports/checkstyle/checkstyle.html
            clevertap-xps/build/reports/checkstyle/checkstyle.html
            clevertap-geofence/build/reports/checkstyle/checkstyle.html
            clevertap-pushTemplates/build/reports/checkstyle/checkstyle.html
            sample/build/reports/checkstyle/checkstyle.html

      - name: Run Unit Tests
        if: always()
        run: ./gradlew :clevertap-core:test

      - name: Upload Unit tests
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results.zip
          path: |
            clevertap-core/build/reports/tests/testDebugUnitTest
            clevertap-hms/build/reports/tests/testDebugUnitTest
            clevertap-xps/build/reports/tests/testDebugUnitTest
            clevertap-geofence/build/reports/tests/testDebugUnitTest
            clevertap-pushTemplates/build/reports/tests/testDebugUnitTest
            sample/build/reports/tests/testDebugUnitTest


      - name: Generate AAR files
        if: always()
        run: ./gradlew :clevertap-core:assembleDebug

      - name: Upload AAR files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results.zip
          path: |
            clevertap-core/build/outputs/aar
            clevertap-hms/build/outputs/aar
            clevertap-xps/build/outputs/aar
            clevertap-geofence/build/outputs/aar
            clevertap-pushTemplates/build/outputs/aar
            sample/build/outputs/aar
